### PR TITLE
Apply project structure to develop branch

### PR DESCRIPTION
**Pull request by leomcabral**
Please review and merge the structure to the develop branch.

### CODE REVIEW

**Comment by samuelcastro** [comment]
That structure doesn't make much sense for me. Why we have 03 api folder (android-api-client, ios-api-client, rest-api)?

My structure would be some thing like:

api
mobile
  -- android
  -- ios
web

**Comment by leomcabral** [comment]
@samuelcastro, there aren't 3 api folders. It's 1 api (REST services) folder and 2 client folders one for android (pure java code) and one for ios (can be in c++ or objective-c).

My proposal intent is to maintain separation of responsibilities in the code itself. 
The clients apis will have the responsibility to handle the communication with the server and provide a higher level of abstraction to the mobiles applications *per se*. As an example the android team (and android code) can focus on implementing the interface and call methods without bothering how to handle the connection and so on.

For sure the code could be merged into de mobile application itself. But I think the separation is handy to others to help with the code if the separation of projects is evident. If someone have java skills, it can modify the android-api-client code, test it and not bother installing any kind of IDE, framework or whatever dependency related to android.

Other interesting point is that we suppose to use http://swagger.io to describe and document the REST API. If we're going to use it why not use it's tools to generate the clients ([whatever]-api-client), it do have tools to do that.

It's important to have some comments of the iOS and Android teams, as they're the most impacted ones. So @matheusruschel, @jhowcs and @felipefcm can you tell what you prefer? In really, it's not a good this we segregate the code in libs if all of you don't feel comfortable with this approach.

Just a last comment: api-client is **not** an api, it's an implementation to access the api (basic a library to access the server).

**Comment by matheusruschel** [comment]
Either way is fine by me!



—

**Comment by felipefcm** [comment]
Initially I don't see any problems with the api/app separate folders, but personally prefer less sibling folders in the root. Maybe we can merge @leomcabral and @samuelcastro ideas:

api
--android
--ios
mobile
--android
--ios
web

Does that make sense?

**Comment by samuelcastro** [comment]
I'm scheduling a meeting with @leomcabral to discuss about that and maybe you guys should joying us.
To be honest, for the nature of that project, I prefer to use a simple approach instead of use "client api", for me this approach will create messy structure and if if understood, we'll create a new request layer, like so:

mobile app > [request] > client-api > [request] > api

And, talking about mobile platform itself, we have big limitation with memory/network/process and so on, so I'm not sure if the @leomcabral's approach is the best one. But I'm open to discuss it, maybe there is misunderstanding in my side and we are a team, so whatever the team decide I'm gonna use for sure.

**Comment by matheusruschel** [comment]
Alright, When should we meet?

**Comment by samuelcastro** [comment]
Just let me know your best time guys, lets see a good one.

**Comment by matheusruschel** [comment]
Everyday from 12 pm to 00 am works for me

**Comment by leomcabral** [comment]
@samuelcastro I think you get it complete wrong. There is no request between the mobile app to the client-api. The project of a client api is not a service that have to be managed. A client api project will result in a *jar* file (I don't know if you are aware of Java terms, but it a *jar* is like a *DLL*).
The mobile apps will only use *objects* that are implemented in a *DLL* (jar in java case).

mobile_app + client-api-lib -> [request] -> api

**Comment by samuelcastro** [comment]
I've already worked with Java (JEE/SE) and you're correct I just got some misunderstanding, is more clear now.

You suggestion make total sense when working in a big project with a big team, I still don't think it will make much sense in our project, because we're small team and so on. 

And, we are not just talking about Java and jars, there is the IOS side, that will be created using swift, but anyway, this is up to you guys, I'll probably have time just to help in the API side, so, feel free to choose whatever you think is better.

**Comment by leomcabral** [comment]
So we can end this thread now. I'll close it and we'll keep it simple for the start. Let's start with @samuelcastro structure:

api
mobile
-- android
-- ios
web

We can expand it later as needed.

**Pull request closed without merging**
